# scratch/test_nurse_workflow.py
import sys
import os
import uuid
import base64
import json
import httpx

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Ensure backend directory is in path
BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend"))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

import database
from database import get_pg_connection

BASE_URL = "http://localhost:5000"

def run_tests():
    print("=" * 75)
    print("CAREPULSE NURSE PORTAL END-TO-END VALIDATION SUITE")
    print("=" * 75)

    # ─────────────────────────────────────────────────────────────────────────
    # 1. VERIFY TRIGGER FUNCTION IN POSTGRESQL (User Requirement 1)
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[1/7] Inspecting PostgreSQL 'generate_staff_code()' Trigger Function...")
    with get_pg_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT pg_get_functiondef(p.oid)
                FROM pg_proc p
                WHERE p.proname = 'generate_staff_code';
            """)
            trigger_row = cur.fetchone()
            if not trigger_row:
                print("❌ FAILED: generate_staff_code trigger not found in PostgreSQL!")
                sys.exit(1)

            trigger_code = list(trigger_row.values())[0] if isinstance(trigger_row, dict) else trigger_row[0]
            print("\n--- ACTUAL POSTGRESQL TRIGGER FUNCTION DEFINITION ---")
            print(trigger_code)
            print("-----------------------------------------------------")

            # Assert that role='nurse' maps explicitly to 'N'
            assert "role_letter := 'N';" in trigger_code or "role_letter := ''N'';" in trigger_code, "Trigger does not map nurse to 'N'!"
            assert "NEW.role = 'nurse'" in trigger_code or "NEW.role = ''nurse''" in trigger_code, "Trigger condition for role='nurse' missing!"
            print("✅ VERIFIED: generate_staff_code() explicitly contains role='nurse' -> role_letter := 'N' (no fallback).")

    # ─────────────────────────────────────────────────────────────────────────
    # 2. RECEPTIONIST CREATING A NURSE VIA API (Checking N-prefix staff_code)
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[2/7] Testing Receptionist creating a Nurse via POST /api/receptionist/nurses...")
    # First login as receptionist
    client = httpx.Client(base_url=BASE_URL, timeout=15.0)

    # Create nurse
    nurse_payload = {
        "name": "Nurse Emily Vance",
        "email": f"emily.{uuid.uuid4().hex[:4]}@carepulse.com",
        "phone": "+91 98765 11223",
        "department": "Triage & Vitals",
        "password": "Nurse@123",
        "hospital_id": "hosp-bag"
    }
    create_nurse_res = client.post("/api/receptionist/nurses", json=nurse_payload)
    print(f"POST /api/receptionist/nurses Status: {create_nurse_res.status_code}")
    assert create_nurse_res.status_code == 200, f"Failed creating nurse: {create_nurse_res.text}"
    nurse_data = create_nurse_res.json()["nurse"]
    staff_code = nurse_data.get("staff_code") or nurse_data.get("staffCode")
    print(f"Created Nurse: {nurse_data['name']} (ID: {nurse_data['id']})")
    print(f"Generated Staff Code: {staff_code}")
    assert staff_code.startswith("N"), f"Staff code '{staff_code}' does NOT start with 'N'!"
    print(f"✅ VERIFIED: Nurse staff code '{staff_code}' correctly starts with 'N' generated by trigger.")

    # List nurses
    list_nurse_res = client.get("/api/receptionist/nurses?hospital_id=hosp-bag")
    assert list_nurse_res.status_code == 200
    nurses_list = list_nurse_res.json()["nurses"]
    print(f"✅ VERIFIED: GET /api/receptionist/nurses returned {len(nurses_list)} nurses for hospital.")

    # ─────────────────────────────────────────────────────────────────────────
    # 3. NURSE AUTHENTICATION & JWT GENERATION
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[3/7] Testing Nurse Authentication via POST /api/staff/login...")
    nurse_login_res = client.post("/api/staff/login", json={
        "email": nurse_payload["email"],
        "password": nurse_payload["password"]
    })
    print(f"POST /api/staff/login Status: {nurse_login_res.status_code}")
    assert nurse_login_res.status_code == 200, f"Nurse login failed: {nurse_login_res.text}"
    login_body = nurse_login_res.json()
    nurse_token = login_body["token"]
    assert login_body["staff"]["role"] == "nurse", f"Staff role is not nurse: {login_body['staff']}"
    print(f"✅ VERIFIED: Nurse login successful! Role: '{login_body['staff']['role']}', Hospital: '{login_body['staff'].get('hospital_id')}'")

    nurse_headers = {"Authorization": f"Bearer {nurse_token}"}

    # ─────────────────────────────────────────────────────────────────────────
    # 4. NURSE QUEUE & PRE-CONSULTATION WORKFLOW
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[4/7] Testing Nurse Queue via GET /api/nurse/queue...")
    queue_res = client.get("/api/nurse/queue?hospital_id=hosp-bag", headers=nurse_headers)
    print(f"GET /api/nurse/queue Status: {queue_res.status_code}")
    assert queue_res.status_code == 200, f"Failed getting queue: {queue_res.text}"
    queue_items = queue_res.json().get("queue", [])
    print(f"Found {len(queue_items)} patient queue items.")

    # If no appointment in queue, create a test appointment for verification
    test_appt_id = None
    test_patient_id = None
    if len(queue_items) > 0:
        test_appt_id = queue_items[0]["appointment_id"]
        test_patient_id = queue_items[0]["patient"]["id"]
    else:
        print("Creating a test appointment in database for nurse vitals test...")
        with get_pg_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT id FROM patients LIMIT 1")
                p_row = cur.fetchone()
                test_patient_id = str(p_row['id']) if (p_row and 'id' in p_row) else (str(p_row[0]) if p_row else str(uuid.uuid4()))
                cur.execute("SELECT id FROM doctors WHERE hospital_id = 'hosp-bag' LIMIT 1")
                d_row = cur.fetchone()
                test_doc_id = str(d_row['id']) if (d_row and 'id' in d_row) else (str(d_row[0]) if d_row else "doc-bag-1")
                test_appt_id = str(uuid.uuid4())
                cur.execute("""
                    INSERT INTO appointments (id, patient_id, doctor_id, hospital_id, date, time, status, queue_status, token_number)
                    VALUES (%s, %s, %s, 'hosp-bag', CURRENT_DATE, '10:00 AM', 'Confirmed', 'Checked In', 101)
                    ON CONFLICT (id) DO NOTHING
                """, (test_appt_id, test_patient_id, test_doc_id))
                conn.commit()

    print(f"Using Appointment ID: {test_appt_id}, Patient ID: {test_patient_id}")

    # ─────────────────────────────────────────────────────────────────────────
    # 5. VITALS ENTRY WITH AUTO-CALCULATED STORED BMI & ABNORMAL FLAGS
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[5/7] Testing Vitals Entry via POST /api/nurse/vitals...")
    vitals_payload = {
        "appointment_id": test_appt_id,
        "patient_id": test_patient_id,
        "height_cm": 175.0,
        "weight_kg": 95.0, # High weight for height -> overweight/obese
        "bp_systolic": 155, # High BP (>140)
        "bp_diastolic": 96, # High BP (>90)
        "heart_rate": 105, # Tachycardia (>100)
        "temperature": 38.6, # Fever (>38.0)
        "temperature_unit": "C",
        "respiratory_rate": 22, # Tachypnea (>20)
        "spo2": 93, # Low SpO2 (<95%)
        "blood_glucose": 145.0,
        "glucose_context": "fasting", # High fasting glucose (>126)
        "notes": "Patient reports shortness of breath and chills."
    }
    vitals_res = client.post("/api/nurse/vitals", json=vitals_payload, headers=nurse_headers)
    print(f"POST /api/nurse/vitals Status: {vitals_res.status_code}")
    assert vitals_res.status_code == 201, f"Failed saving vitals: {vitals_res.text}"
    v_data = vitals_res.json()["vitals"]
    abnormal_flags = vitals_res.json()["abnormal_flags"]
    print(f"Saved Vitals Record ID: {v_data['id']}")
    print(f"Auto-calculated BMI: {v_data['bmi']} kg/m² (Expected ~31.0)")
    print(f"Abnormal Flags ({len(abnormal_flags)} detected):")
    for flag in abnormal_flags:
        print(f"   ⚠️  {flag}")
    assert len(abnormal_flags) >= 5, f"Expected multiple abnormal flags, got: {abnormal_flags}"
    assert float(v_data['bmi']) > 30.0, f"Expected BMI > 30, got {v_data['bmi']}"
    print("✅ VERIFIED: Vitals stored with auto-computed BMI and accurate clinical abnormal screening flags.")

    # ─────────────────────────────────────────────────────────────────────────
    # 6. REPORT UPLOAD VIA BASE64 & DIAGNOSTIC LAB TEST ENTRY
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[6/7] Testing Report Upload (Base64) & Diagnostic Lab Test Entry...")
    # Base64 report upload (User Requirement 3)
    sample_content = b"CarePulse Lab Test Report - CBC & Metabolic Panel. Patient: PT-101. Normal WBC."
    sample_b64 = "data:application/pdf;base64," + base64.b64encode(sample_content).decode("utf-8")

    upload_res = client.post("/api/nurse/upload-report", json={
        "file_data": sample_b64,
        "filename": "cbc_report.pdf",
        "appointment_id": test_appt_id
    }, headers=nurse_headers)
    print(f"POST /api/nurse/upload-report Status: {upload_res.status_code}")
    assert upload_res.status_code == 200, f"Report upload failed: {upload_res.text}"
    report_file_url = upload_res.json()["file_url"]
    print(f"Uploaded Report URL: {report_file_url}")
    assert report_file_url.startswith("/static_downloads/lab_reports/"), f"Unexpected URL: {report_file_url}"
    print("✅ VERIFIED: Report uploaded successfully using established base64 decoding pattern.")

    # Record lab test
    test_res = client.post("/api/nurse/tests", json={
        "appointment_id": test_appt_id,
        "patient_id": test_patient_id,
        "test_type": "Complete Blood Count (CBC)",
        "structured_results": {
            "Hemoglobin": {"value": "13.8", "unit": "g/dL"},
            "WBC": {"value": "8200", "unit": "/uL"}
        },
        "free_text_result": "WBC and Platelets within standard reference limits.",
        "file_url": report_file_url,
        "status": "completed"
    }, headers=nurse_headers)
    print(f"POST /api/nurse/tests Status: {test_res.status_code}")
    assert test_res.status_code == 201, f"Failed saving lab test: {test_res.text}"
    print("✅ VERIFIED: Diagnostic test recorded.")

    # Doctor Consultation Prep Integration
    prep_res = client.get(f"/api/doctor/consultation-prep/{test_appt_id}", headers=nurse_headers)
    assert prep_res.status_code == 200, f"Doctor prep failed: {prep_res.text}"
    prep_data = prep_res.json()
    assert prep_data["has_vitals"] is True, "Doctor consultation prep missing vitals!"
    assert len(prep_data["lab_tests"]) >= 1, "Doctor consultation prep missing lab tests!"
    print(f"✅ VERIFIED: Doctor Consultation Prep pre-populates {len(prep_data['abnormal_flags'])} abnormal flags and {len(prep_data['lab_tests'])} lab tests.")

    # ─────────────────────────────────────────────────────────────────────────
    # 7. CRITICAL RBAC BOUNDARY ENFORCEMENT (User Requirement 4)
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[7/7] Testing CRITICAL RBAC Boundaries: Nurse write attempts on Doctor & Receptionist endpoints...")

    # Test A: Nurse attempting doctor consultation write endpoint (POST /api/doctor/consultations)
    print("  -> Attempting POST /api/doctor/consultations as Nurse...")
    doc_write_res = client.post("/api/doctor/consultations", json={
        "patientId": test_patient_id,
        "doctorId": "doc-bag-1",
        "doctorName": "Dr. Attending",
        "soapData": {"assessment": "Prescription attempted by nurse"}
    }, headers=nurse_headers)
    print(f"     Status: {doc_write_res.status_code} (Expected: 403 Forbidden)")
    assert doc_write_res.status_code == 403, f"SECURITY VIOLATION: Nurse was NOT rejected with 403 on doctor consultations! Got: {doc_write_res.status_code}"
    print(f"     Response Detail: {doc_write_res.json().get('detail')}")
    print("     ✅ CORRECTLY REJECTED WITH 403 FORBIDDEN.")

    # Test B: Nurse attempting consultation write via /api/consultations
    print("  -> Attempting POST /api/consultations as Nurse...")
    main_consult_res = client.post("/api/consultations", json={
        "patientId": test_patient_id,
        "doctorId": "doc-bag-1",
        "doctorName": "Dr. Attending",
        "soapData": {"assessment": "Prescription attempted by nurse"}
    }, headers=nurse_headers)
    print(f"     Status: {main_consult_res.status_code} (Expected: 403 Forbidden)")
    assert main_consult_res.status_code == 403, f"SECURITY VIOLATION: Nurse was NOT rejected with 403 on /api/consultations! Got: {main_consult_res.status_code}"
    print(f"     Response Detail: {main_consult_res.json().get('detail')}")
    print("     ✅ CORRECTLY REJECTED WITH 403 FORBIDDEN.")

    # Test C: Nurse attempting receptionist doctor creation (POST /api/receptionist/doctors)
    print("  -> Attempting POST /api/receptionist/doctors as Nurse...")
    rec_write_res = client.post("/api/receptionist/doctors", json={
        "name": "Dr. Hacker Unauthorized",
        "specialty": "Cardiology",
        "department": "Cardiology"
    }, headers=nurse_headers)
    print(f"     Status: {rec_write_res.status_code} (Expected: 403 Forbidden)")
    assert rec_write_res.status_code == 403, f"SECURITY VIOLATION: Nurse was NOT rejected with 403 on create doctor! Got: {rec_write_res.status_code}"
    print(f"     Response Detail: {rec_write_res.json().get('detail')}")
    print("     ✅ CORRECTLY REJECTED WITH 403 FORBIDDEN.")

    # Test D: Nurse attempting doctor availability / schedule change (PATCH /api/receptionist/doctors/{id}/availability)
    print("  -> Attempting PATCH /api/receptionist/doctors/doc-bag-1/availability as Nurse...")
    avail_write_res = client.patch("/api/receptionist/doctors/doc-bag-1/availability", json={
        "isAvailable": False
    }, headers=nurse_headers)
    print(f"     Status: {avail_write_res.status_code} (Expected: 403 Forbidden)")
    assert avail_write_res.status_code == 403, f"SECURITY VIOLATION: Nurse was NOT rejected with 403 on availability toggle! Got: {avail_write_res.status_code}"
    print(f"     Response Detail: {avail_write_res.json().get('detail')}")
    print("     ✅ CORRECTLY REJECTED WITH 403 FORBIDDEN.")

    # Test E: Nurse attempting to create another staff member (POST /api/receptionist/nurses)
    print("  -> Attempting POST /api/receptionist/nurses as Nurse...")
    nurse_create_nurse_res = client.post("/api/receptionist/nurses", json={
        "name": "Nurse Unauthorized Junior",
        "email": "junior@carepulse.com"
    }, headers=nurse_headers)
    print(f"     Status: {nurse_create_nurse_res.status_code} (Expected: 403 Forbidden)")
    assert nurse_create_nurse_res.status_code == 403, f"SECURITY VIOLATION: Nurse was NOT rejected with 403 on creating staff! Got: {nurse_create_nurse_res.status_code}"
    print(f"     Response Detail: {nurse_create_nurse_res.json().get('detail')}")
    print("     ✅ CORRECTLY REJECTED WITH 403 FORBIDDEN.")

    print("\n" + "=" * 75)
    print("🎉 ALL 7 TEST SUITES & RBAC PERMISSION BOUNDARIES PASSED PERFECTLY!")
    print("=" * 75)

if __name__ == "__main__":
    run_tests()
